### ISSUE TITLE
Message Malformed Error

### ISSUE THREAD

**Issue by ctownj30** [brigger/HomeAssistant_Blueprints#1]
For some reason I'm getting the following error:

Message malformed: Entity IDs cannot be None for dictionary value @ data['action'][0]['choose'][0]['conditions'][1]['entity_id']

Here's the YAML I'm trying to save:

```
description: ""
use_blueprint:
  path: brigger/advanced_custom_motion_sensor.yaml
  input:
    motion_entity:
      - binary_sensor.carport_motion_inward_sensor
      - binary_sensor.carport_motion_outward_sensor
    no_motion_wait: 60
    light_target:
      device_id: df6e2530e1ed8b0785923dbb2e6c6796
alias: Garage - Motion - Garage Lights On Any Time
```

and the UI:

![image](https://github.com/brigger/HomeAssistant_Blueprints/assets/21022303/411140f5-fe8a-4871-96c2-95097db62c74)

![image](https://github.com/brigger/HomeAssistant_Blueprints/assets/21022303/48fd0a55-4331-4aa8-baa0-12f98e02ce06)

Hoping for a fix - this is exactly what I was looking for.
